version: '3.9'

services:
  python:
    build: .
    ports:
      - "5000:5000"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"